package com.rainbowforest.telegramservice.bot;

public enum BotState {
    NONE,
    WAITING_FOR_PRODUCT_NAME,
    WAITING_FOR_PRODUCT_PRICE,
    WAITING_FOR_VARIANT_INFO,
    WAITING_FOR_SPEC_INFO,
    WAITING_FOR_PRODUCT_MEDIA,
    WAITING_FOR_DELETE_VAR_SPEC,
    WAITING_FOR_PRIMARY_IMAGE,
    WAITING_FOR_PRODUCT_QUANTITY
}
